### PR TITLE
Adding function to calculate 3 eigenvectors

### PR DESCRIPTION
**Pull request by spiessbuerger**
This function would make it easier to get all 3 eigenvectors in one run. Not sure if this is the most desirable implementation, and would gladly still make changes to it.

### CODE REVIEW

**Comment by spiessbuerger** [comment]
I just noticed that I am not returning the eigenvalue, which I would need too. Will make another commit later today.

**Comment by spiessbuerger** [comment]
Now the function also returns the eigenvalues. Everything is in a list. Do you think I should return the 3 rows separately?

**Comment by joferkington** [comment]
Sorry for my delay in replying!

This is definitely a useful function!  I've changed the way it works a bit and added tests.  See 1b00f1f9d3cc639c773191f52d809cd4ae11e014, 447141e974e04133575f7f1a0bb9b0d7c9593083, 1a36aa128eef6beccdc444ad2318c35a39e63c83, and 5c2ea01c843a35a15daae1840eeec79dca4c0fde 

Thanks again for the pull request!

**Comment by spiessbuerger** [comment]
Thanks for improving the code. Looks really good now.

**Pull request merged**
