### PR TITLE
add package for slope stability - kinematic analysis

### PR DESCRIPTION
**Pull request by ricsatjr**
Hi Joe, 

You may be interested in adding this package.  I am currently exploring a more active role in developing/extending the mplstereonet package as part of my teaching and research work here at the University of the Philippines. By the way, I've licensed this under GNU GPLv3. 

Disclaimer: I have some background in Python, but I am still familiarizing myself with the formal structuring of packages and modules. 

Cheers,

Ric

### CODE REVIEW

**Comment by joferkington** [comment]
Hi Ric,

Sorry for my delay in replying!

First off, great stuff, and I'd love to include it.  

However, I can't distribute the GPL licensed code along with the rest of `mplstereonet`, as the rest of the codebase is under an MIT license.  By including GPL-licensed code along with it, the rest of the code would effectively be under the GPL as well.  (More precisely, it would have the additional restrictions that the GPL has and would prevent anything in `mplstereonet` from being used in proprietary applications.)

There are a few ways this could be handled.  

  1. You could create a separate python package that depends on `mplstereonet` and distribute it separately (presumably through PyPi, so that `pip install` picks it up).
  2. You could change this to be under the same license as the rest of `mplstereonet`.
 
I'd be happy to help with either of those!  

If you do decide to change the license and include it in `mplstereonet`, there are some naming conventions we'd need to work on, to match general Python practices (e.g. Python doesn't use naming prefixes like `KA_function_name`, instead it uses namespaces like `kinematic_analysis.function_name`).  I'd argue this would make a good fit with the rest of the analysis-related functions under `mplstereonet.analysis`.

At any rate, thanks!

**Comment by ricsatjr** [comment]
Hi Joe,

I am initially inclined to pursue this project with the GPL license option,
but I am open to more discussion on licensing.  I am curious, though, that
your license reads (c) 2012 Free Software Foundation. Are you in anyway
related to the group? And if I am not mistaken, I think an MIT license is
not compatible with FSF's principles.

Thanks for your interest.

**Comment by ricsatjr** [comment]
May I post another question?

If I go through with contributing to mplstereonet under your MIT license,
how would an attribution to my contribution look like? I am not quite
concerned about financial/commercial interests. But since I teach at the
University, any intellectual output counts when it comes to promotions and
tenure issues. Do you have any experience of having software
subpackages/modules cited as intellectual works in the academe?

**Comment by ricsatjr** [comment]
Hi Joe,

I was looking at the licenses available. For option #2 that you presented,
would an LGPL <https://www.gnu.org/licenses/lgpl.html> be amenable to you?

**Comment by joferkington** [comment]
Sorry for the delay again.  Got a bit caught up in work the past few days.

For LGPL, the main issue is that your code would be distributed along with the rest of `mplstereonet`, which would cause the entire project to become LGPL.  The LGPL allows linking and binary redistribution, but any modifications and code that is mixed with the LGPL code must stay LGPL.  Unfortunately, it's difficult to distribute LGPL code intermingled with MIT licensed code without the entire project effectively becoming LGPL.

It's critical that `mplstereonet` be usable by proprietary applications.  LGPL does allow that to a degree, and it's a better choice than GPL for a library (as opposed to an end-user focused application).  However, MIT and BSD style licenses are more flexible than LGPL in that regard, and they're the standard in the Python community (particularly scientific python).  I'd prefer to keep the additional flexibility that an MIT license provides end-users, and even if I didn't, I'd have to get permission for everyone else who has ever contributed to change the license of the rest of the code to LGPL.

As far as the copyright assignment to the FSF, there are projects where the FSF is assigned copyright even when the license isn't GPL or LGPL (e.g. `ncurses` is an FSF project under an MIT license). However, the FSF copyright attribution in the license for `mplstereonet` is incorrect.  I haven't signed a copyright assignment form, so it can't be listed as FSF copyright.  I suspect I originally copy-pasted the license and forgot to change the copyright assignment.  It should be listed as "Copyright mplstereonet developers" (i.e. each individual contributor retains their copyright).

As far as copyleft vs permissive licenses (e.g. LGPL vs BSD or MIT), I chose a permissive license for two reasons: 1) I wanted `mplstereonet` to be usable by the widest possible audience (i.e. proprietary as well as open source applications), and 2) the scientific python community as a whole tends to use permissive liceneses.  For example, Python and all widely-used Python libraries are under permissive licenses (e.g. BSD, PSF, MIT, etc, all of which allow proprietary modifications and binary redistribution). 

Finally for the citation side, it varies.  However, at least in my field `mplstereonet` as a whole isn't citable, as there's never been a publication dedicated to it. (Most journals in structural geology won't allow citing a piece of software unless there's a publication related to it.)  In other fields, citing a software project is perfectly fine.  However, it would be difficult to cite just your portion of the project specifically.  

If easy citeability is a concern, a good option would be to write a short article on just your kinematic analysis portion.  Regardless of whether or not you choose to include that portion as a part of `mplstereonet` or as an independent package, having a publication focused on just the kinematic analysis portion will ensure that your contribution remains independently citable.

Hope that clarifies things a bit, and thanks again!
-Joe

**Comment by ricsatjr** [comment]
Hi.

Thanks for the insights. I think I'm OK with shifting to the MIT license.I
hope we could discuss how to move forward on this. May be a road map?  But
no hurries, as I intend to go about the development at a convenient pace
during my free time.

Thanks.

**Pull request closed without merging**
